### ISSUE TITLE
Uncaught (in promise) TypeError: blobToBase64 is not a function

### ISSUE THREAD

**Issue by kidmysoul** [tiaanduplessis/blob-to-base64#13]
After update to 1.0.2  I got above error.

**Comment by dineshmaths1** [comment]
me tooo

**Comment by k2font** [comment]
me too
